### ISSUE TITLE
CC1 and CC2 Voltage Level Mismatch

### ISSUE THREAD

**Issue by chlee75** [tejv/USBCx#1]
CC1 and CC2 voltage level are different from actual CC1/CC2 voltage level in USBCx 2.1.0.
For example, CC1 is 390 mV and CC2 is 416 mV while actual CC1 is 4.986mV (VCONN) and CC2 is 1.570mV (CC).

**Comment by tejv** [comment]
Please check you HW version rev5 board is needed for this feature.
Also CC1/CC2 readings will saturate max at 3.3V.

**Comment by chlee75** [comment]
Hi. Tejender

I am Ryan who is Cypress AE in Korea.
I am glad to meet you again.

I checked HW and I fixed CC voltage issue.

Your PD Analyzer is very helpful for me to work on Type-C.
Do you have any plan to develop real time XScope?

Thanks a lot.



2017-09-28 12:34 GMT+09:00 Tejender Sheoran <notifications@github.com>:

**Comment by tejv** [comment]
Hi Ryan,
right now i have no plan to work on Xscope.
